name: collections
<<<<<<< HEAD
description: A sample command-line application.
=======
description: A simple command-line application.
>>>>>>> 5187fee5670d57dfaa97af6764a6afee8c6964a4
version: 1.0.0
# homepage: https://www.example.com

environment:
<<<<<<< HEAD
  sdk: '>=2.15.1 <3.0.0'
=======
  sdk: '>=2.16.1 <3.0.0'
>>>>>>> 5187fee5670d57dfaa97af6764a6afee8c6964a4


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
<<<<<<< HEAD
  test: ^1.16.0
=======
>>>>>>> 5187fee5670d57dfaa97af6764a6afee8c6964a4
